# Définition de l'image de base (Légère et rapide)
image: docker:24.0.5

# Définition des services (On utilise Docker dans Docker pour tester ton docker-compose)
services:
  - docker:24.0.5-dind

stages:
  - static_analysis
  - infrastructure_check

# Étape 1 : Analyse du code (Linting)
php_linting:
  stage: static_analysis
  image: php:8.2-cli
  script:
    - echo "Analyse syntaxique du code PHP en cours..."
    - find . -name "*.php" -not -path "./vendor/*" | xargs -n 1 php -l

# Étape 2 : Test de l'infrastructure Docker
docker_compose_check:
  stage: infrastructure_check
  script:
    - echo "Vérification de la validité du fichier docker-compose.yml..."
    - docker compose config
    - echo "Simulation du build de l'image PsySpace..."
    - docker compose build