name: PsySpace CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification syntaxe PHP
        run: |
          find . -name "*.php" -not -path "./vendor/*" | xargs -n 1 php -l

      - name: Test Docker
        run: |
          docker compose version
          docker compose config